/* Generated stubs. The chain-order test never calls these; they exist so the
   real jdspController.c can be linked without the whole engine. */
void AgcProcess(void) {}
void ArbitraryResponseEqualizerEnable(void) {}
void Convolver1DLoadImpulseResponse(void) {}
void CrossfeedEnable(void) {}
void DDCProcess(void) {}
void DiffSurroundProcess(void) {}
void FFTConvolver1x1Free(void) {}
void FFTConvolver1x1Init(void) {}
void FFTConvolver1x1LoadImpulseResponse(void) {}
void FFTConvolver1x1Process(void) {}
void FetCompProcess(void) {}
void LiveProgProcessSlot(void) {}
void MultimodalEqualizerEnable(void) {}
void MultimodalEqualizerProcess(void) {}
void NSEEL_quit(void) {}
void NSEEL_start(void) {}
void PitchShiftProcess(void) {}
void SpeakerOptProcess(void) {}
void VReverbProcess(void) {}
void ViperBassProcess(void) {}
void ArbitraryResponseEqualizerProcess(void) {}
void BassBoostProcess(void) {}
void BassExciterProcess(void) {}
void CompressorProcess(void) {}
void CrossfeedProcess(void) {}
void CureProcess(void) {}
void EchoDelayProcess(void) {}
void FieldSurroundProcess(void) {}
void HpSurroundProcess(void) {}
void LiveProgProcess(void) {}
void MaximizerProcess(void) {}
void MultibandDistProcess(void) {}
void ReverbProcess(void) {}
void SpectrumExtensionProcess(void) {}
void StereoEnhancementProcess(void) {}
void VDynBassProcess(void) {}
void VacuumTubeProcess(void) {}
void ViperClarityProcess(void) {}
void psrc_clone(void) {}
void psrc_generate(void) {}
void BassExciterSetParam(void) {}
void CCConv(void) {}
void JLimiterInit(void) {}
void JamesDSPOfflineResampling(void) {}
void SpectrumExtensionSetParam(void) {}
void ccconv1Gain(void) {}
void ccconv2Gain(void) {}
void ccconv3Gain(void) {}
void ccconv4Gain(void) {}
void channel_splitFloat(void) {}
void compressedLen_CCConv(void) {}
void compressedLen_jdspImp(void) {}
void drflac_close(void) {}
void drflac_open_memory(void) {}
void drflac_read_pcm_frames_f32(void) {}
void hrtfFs(void) {}
void hrtfLenPerChannel(void) {}
void jdspImp(void) {}
void psrc_filt_stereo(void) {}
void psrc_free(void) {}
void AgcSetParam(void) {}
void BassExciterSetParam2(void) {}
void CompressorConstructor(void) {}
void CompressorDisable(void) {}
void CureSetParam(void) {}
void DiffSurroundSetParam(void) {}
void EchoDelaySetParam(void) {}
void FetCompSetParam(void) {}
void FieldSurroundSetParam(void) {}
void HpSurroundSetParam(void) {}
void JLimiterSetCoefficients(void) {}
void LiveProgConstructor(void) {}
void MaximizerSetParam(void) {}
void MultibandDistSetParam(void) {}
void PitchShiftSetParam(void) {}
void SpeakerOptSetParam(void) {}
void VDynBassSetParam(void) {}
void VReverbSetParam(void) {}
void ViperBassSetParam(void) {}
void ViperClaritySetParam(void) {}
void ArbitraryResponseEqualizerConstructor(void) {}
void ArbitraryResponseEqualizerDisable(void) {}
void BassBoostConstructor(void) {}
void BassBoostDisable(void) {}
void BassBoostSetParam(void) {}
void Convolver1DConstructor(void) {}
void CrossfeedChangeMode(void) {}
void CrossfeedConstructor(void) {}
void CrossfeedDisable(void) {}
void DDCConstructor(void) {}
void DDCDisable(void) {}
void LiveProgDisable(void) {}
void MultimodalEqualizerConstructor(void) {}
void ReverbDisable(void) {}
void Reverb_SetParam(void) {}
void StereoEnhancementConstructor(void) {}
void StereoEnhancementDisable(void) {}
void StereoEnhancementSetParam(void) {}
void VacuumTubeDisable(void) {}
void VacuumTubeSetGain(void) {}
void ArbitraryResponseEqualizerDestructor(void) {}
void CompressorDestructor(void) {}
void CompressorEnable(void) {}
void Convolver1DDestructor(void) {}
void CrossfeedDestructor(void) {}
void DDCDestructor(void) {}
void DDCEnable(void) {}
void DiffSurroundDisable(void) {}
void EchoDelayDisable(void) {}
void HpSurroundDisable(void) {}
void LiveProgDestructor(void) {}
void MaximizerDisable(void) {}
void MultibandDistDisable(void) {}
void MultimodalEqualizerDisable(void) {}
void PitchShiftDisable(void) {}
void StereoEnhancementDestructor(void) {}
void StereoEnhancementRefresh(void) {}
void VReverbDisable(void) {}
void db2magf(void) {}
void randXorshift(void) {}
void MultimodalEqualizerDestructor(void) {}
